### ISSUE TITLE
the properties listed in the readme dont match the tests

### ISSUE THREAD

**Issue by azmuth94** [learn-co-curriculum/objc-fissentence#4]
the properties listed in the readme dont match the tests

**Comment by AnnJohn** [comment]
Thanks @azmuth94 for raising the issue. @markedwardmurray could you take a look at this issue? Close too if you can. Thanks.

**Comment by markedwardmurray** [comment]
@azmuth94 it's possible that you forked and cloned right before i deployed the rewrite which changed the property names. The new version is also significantly easier. Which batch are you are in? I can't find your student profile on Learn.co
